---
title: ""
#subtitle: "A subtitle"
thanks: ""
author:
- name: Jason Lam
  student_number: 400201299
- name: 
  student_number: 
- name: 
  student_number: 
- name: 
  student_number: 
- name: 
  student_number: 
subject: "ENVSOCTY 4GA3"
abstract: "This paper reports our analysis of opioid prescriptions in Kentucky, USA, and its relationship with income and education at the level of counties. Data were obtained from the Washington Post database and the US Census."
keywords: "opioids, education, income, spatial analysis"
date: "4/22/2022"
output:
  pdf_document:
    # The project-template-default.tex file was minimally adapted from Steven V. Miller's template for academic manuscripts. See:
    # http://svmiller.com/blog/2016/02/svm-r-markdown-manuscript/
    # https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-latex-ms.tex
    template: project-template-default.tex
bibliography: [bibliography.bib, packages.bib]
always_allow_html: true
---

<!--Chunks of code can have names; the chunk option "include" controls whether the chunk and its output are printed in the final document-->
```{r load-packages, include=FALSE}

```

```{r write-package-bib, include=FALSE}
# This function is used to write a bibliography for the `R` packages used in the paper
knitr::write_bib(file = 'packages.bib')
```

```{r read-census-data, include=FALSE}
income_fip <- read_excel("data/income.fip.xlsx")
education_ky <- read_excel("data/education_ky.xlsx")
```

<!--This create a page break, i.e., starts a new page-->
<!--\newpage-->

<!-- 
To cite references in your bibliography.bib file, use [@item] if you want it to be cited in brackets, or @item if you want it to be cited as Name (year). If you want to cite various items in brackets, separate them with semicolons [@item1; @item2]
-->


# Introduction


# Study area


# Data


# Methods


# Results



# Analysis


# Conclusion



# References
